general:
  name: default
  project_name: MetricsHacking
  cfg_dir: cfgs/default.yaml
  datalen_train: 11000
  datalen_test: 1500
  max_epoch: 35
  patience: 6
  batch_size_train: 8
  batch_size_test: 4
  project_dir: .
  quality: 1
  mode: Train
  break_flag: 0
  center_crop: 0
  codec: cheng2020_attn
  dataset_dir: 'P:/vimeo_triplet/sequences/'
  dataset_type: img
  od_vgan_model_path: "../OD_VGAN/model_zoo/model_H264n_1step_vimeo90kIframe_noisntancenorm_deletedallnorm_jpegp3_d.ckpt"
  enhance: 1
  enhance_net: smallnet_skips
  eta_min: 1.0e-05
  sigmoid_activation: 1
  home_dir: ./home_dir/
  k_lst:
  - 1.0
  logs_dir: logs/
  lr_linear_stage: 3
  met_names:
  - DISTS
  minimal_batch_sz: 0
  optimize_image: 0
  optimizer: AdamW
  optimizer_opt:
    lr: 0.001
  order_pre_post: 0
  patch_sz: 256
  save_net_enhance: 1
  save_netcodec: 0
  to_crop: 1
  use_wandb: 1
  codec_metric: mse
  codec_pretrained: 1
  ckpt_recovery: 0
  blur_sigma_min: 2.0
  blur_sigma_max: 2.0
  blur_sz_min: 5
  blur_sz_max: 5
  num_workers: 0
  ckpt_recovery_path: ""
  train_mode: 1
  save_ckpt: 1
  save_enh: 0
  save_out: 0
  comment: ""
run:
  device: "cuda:0"
  device_met : "cuda:0"
  device_enh : "cuda:0"
  device_sub : "cpu"
